// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RINHABACKEND.Data;

#nullable disable

namespace RINHABACKEND.Migrations
{
    [DbContext(typeof(Databasecontext))]
    partial class DatabasecontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RINHABACKEND.Model.Saldo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Data_extrato")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Total")
                        .HasColumnType("integer");

                    b.Property<int>("limite")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Saldos");
                });

            modelBuilder.Entity("RINHABACKEND.Model.Transacao", b =>
                {
                    b.Property<Guid>("transacaoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<DateTime>("Realizada_em")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SaldoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<int>("Valor")
                        .HasColumnType("integer");

                    b.HasKey("transacaoID");

                    b.HasIndex("SaldoId");

                    b.ToTable("Transacoes");
                });

            modelBuilder.Entity("RINHABACKEND.Model.Transacao", b =>
                {
                    b.HasOne("RINHABACKEND.Model.Saldo", null)
                        .WithMany("UltimasTransacoes")
                        .HasForeignKey("SaldoId");
                });

            modelBuilder.Entity("RINHABACKEND.Model.Saldo", b =>
                {
                    b.Navigation("UltimasTransacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
